# Generated by Django 4.1.7 on 2023-03-16 22:48

import chat_module.models.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_profiles", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[chat_module.models.validators.age_validation],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        null=True,
                        validators=[chat_module.models.validators.gender_validation],
                    ),
                ),
                (
                    "gender_focus",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("E", "Everyone")],
                        default="E",
                        max_length=10,
                        validators=[
                            chat_module.models.validators.gender_focus_validation
                        ],
                    ),
                ),
                ("country", models.TextField(default="USA", null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="America/New_York",
                        max_length=32,
                        validators=[chat_module.models.validators.timezone_validation],
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            chat_module.models.validators.experience_validation
                        ],
                    ),
                ),
                (
                    "interests",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        validators=[chat_module.models.validators.interests_validation],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True, default="")),
            ],
        ),
        migrations.CreateModel(
            name="DeletedChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.JSONField(blank=True)),
                ("input_chars", models.IntegerField(default=0)),
                (
                    "level",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=5,
                        validators=[chat_module.models.validators.level_validation],
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_profiles.botprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.JSONField(blank=True, default=list)),
                ("input_chars", models.IntegerField(default=0)),
                (
                    "level",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=5,
                        validators=[chat_module.models.validators.level_validation],
                    ),
                ),
                ("user_summary", models.JSONField(blank=True, default=list)),
                ("bot_summary", models.JSONField(blank=True, default=list)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_profiles.botprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "bot")},
            },
        ),
    ]
