# Generated by Django 4.1.7 on 2023-03-24 00:29

import chat_module.models.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.JSONField(blank=True)),
                ("input_chars", models.IntegerField(default=0)),
                (
                    "level",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=5,
                        validators=[chat_module.models.validators.level_validation],
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_profiles.botprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("history", models.JSONField(blank=True, default=list)),
                ("input_chars", models.IntegerField(default=0)),
                (
                    "level",
                    models.DecimalField(
                        decimal_places=4,
                        default=1.0,
                        max_digits=5,
                        validators=[chat_module.models.validators.level_validation],
                    ),
                ),
                ("user_summary", models.JSONField(blank=True, default=list)),
                ("bot_summary", models.JSONField(blank=True, default=list)),
                ("summary_index", models.IntegerField(default=-1, null=True)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_profiles.botprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "bot")},
            },
        ),
    ]
