# Generated by Django 4.1.7 on 2023-03-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat_module",
            "0002_remove_userprofile_email_remove_userprofile_username_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="username",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
