# Generated by Django 4.1.7 on 2023-03-17 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat_module", "0002_chathistory_bot_summary_index_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chathistory",
            old_name="user_summary_index",
            new_name="summary_index",
        ),
        migrations.RemoveField(
            model_name="chathistory",
            name="bot_summary_index",
        ),
    ]
