# Generated by Django 4.1.7 on 2023-03-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat_module", "0003_remove_userprofile_name_userprofile_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
    ]
