# Generated by Django 4.1.7 on 2023-03-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_module", "0003_chathistory_input_chars"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="level",
        ),
        migrations.AddField(
            model_name="chathistory",
            name="level",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="chathistory",
            name="progress",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="experience",
            field=models.IntegerField(default=0),
        ),
    ]
