# Generated by Django 4.1.7 on 2023-03-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_module", "0004_remove_userprofile_level_chathistory_level_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chathistory",
            name="progress",
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="level",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
    ]
