# Generated by Django 4.1.7 on 2023-03-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_module", "0004_remove_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="UID",
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
