# Generated by Django 4.1.7 on 2023-03-13 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat_module", "0005_alter_userprofile_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="UID",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="gender_focus",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=None,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="level",
            field=models.CharField(default=1, max_length=50),
        ),
    ]
