# Generated by Django 4.1.7 on 2023-03-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_module", "0006_userprofile_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="deletedchathistory",
            name="input_chars",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="deletedchathistory",
            name="level",
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="chathistory",
            name="history",
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender_focus",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
