# Generated by Django 4.1.7 on 2023-03-15 05:18

import chat_module.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat_module", "0007_deletedchathistory_input_chars_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chathistory",
            name="level",
            field=models.DecimalField(
                decimal_places=4,
                default=1.0,
                max_digits=5,
                validators=[chat_module.models.level_validation],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(
                blank=True, null=True, validators=[chat_module.models.age_validation]
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
                validators=[chat_module.models.gender_validation],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender_focus",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=10,
                null=True,
                validators=[chat_module.models.gender_validation],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[chat_module.models.interests_validation],
            ),
        ),
    ]
