# Generated by Django 4.1.7 on 2023-03-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BotProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=1)),
                ("age", models.IntegerField()),
                ("hobbies", models.JSONField()),
                ("favorites", models.JSONField()),
            ],
        ),
    ]
