# Generated by Django 4.1.7 on 2023-03-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="profile_image",
            field=models.ImageField(default=None, upload_to="images/"),
            preserve_default=False,
        ),
    ]
