# Generated by Django 4.1.7 on 2023-04-04 02:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_profiles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botprofile",
            name="profile_image",
        ),
    ]
