# Generated by Django 4.1.7 on 2023-03-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0005_remove_botprofile_profession"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="profession",
            field=models.TextField(null=True),
        ),
    ]
