# Generated by Django 4.1.7 on 2023-03-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0006_botprofile_profession"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botprofile",
            name="id",
        ),
        migrations.AddField(
            model_name="botprofile",
            name="name",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="botprofile",
            name="bot_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
