# Generated by Django 4.1.7 on 2023-03-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0007_remove_botprofile_id_botprofile_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="bio",
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
