# Generated by Django 4.1.7 on 2023-03-14 10:24

import ai_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0008_botprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botprofile",
            name="favorites",
            field=models.JSONField(validators=[ai_profiles.models.validate_json]),
        ),
        migrations.AlterField(
            model_name="botprofile",
            name="hobbies",
            field=models.JSONField(validators=[ai_profiles.models.validate_json]),
        ),
    ]
