# Generated by Django 4.1.7 on 2023-03-14 10:29

import ai_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0009_alter_botprofile_favorites_alter_botprofile_hobbies"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botprofile",
            name="profile_image",
            field=models.ImageField(
                upload_to="images/",
                validators=[ai_profiles.models.validate_image_extension],
            ),
        ),
    ]
