# Generated by Django 4.1.7 on 2023-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0010_alter_botprofile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botprofile",
            name="profession",
            field=models.TextField(),
        ),
    ]
