# Generated by Django 4.1.7 on 2023-03-14 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0011_alter_botprofile_profession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botprofile",
            name="gender",
            field=models.CharField(
                max_length=1,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Gender must be either M or F", regex="^[MF]$"
                    )
                ],
            ),
        ),
    ]
