# Generated by Django 4.1.7 on 2023-03-14 11:48

import ai_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0012_alter_botprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="botprofile",
            name="physical_attributes",
            field=models.JSONField(
                default=None, validators=[ai_profiles.models.validate_json]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="botprofile",
            name="age",
            field=models.IntegerField(validators=[ai_profiles.models.validate_age]),
        ),
        migrations.AlterField(
            model_name="botprofile",
            name="name",
            field=models.CharField(
                max_length=50, validators=[ai_profiles.models.validate_name]
            ),
        ),
    ]
