# Generated by Django 4.1.7 on 2023-03-14 11:49

import ai_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_profiles",
            "0013_botprofile_physical_attributes_alter_botprofile_age_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="botprofile",
            name="physical_attributes",
            field=models.JSONField(
                blank=True, null=True, validators=[ai_profiles.models.validate_json]
            ),
        ),
    ]
