# Generated by Django 4.1.7 on 2023-03-14 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0014_alter_botprofile_physical_attributes"),
    ]

    operations = []
