# Generated by Django 4.1.7 on 2023-03-14 11:52

import ai_profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_profiles", "0015_auto_20230314_0750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botprofile",
            name="physical_attributes",
            field=models.JSONField(validators=[ai_profiles.models.validate_json]),
        ),
    ]
