# Generated by Django 4.1.7 on 2023-03-19 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profiles.models.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.TextField(blank=True, default="")),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[user_profiles.models.validators.age_validation],
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        null=True,
                        validators=[user_profiles.models.validators.gender_validation],
                    ),
                ),
                (
                    "gender_focus",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("E", "Everyone")],
                        default="E",
                        max_length=10,
                        validators=[
                            user_profiles.models.validators.gender_focus_validation
                        ],
                    ),
                ),
                ("country", models.TextField(default="USA", null=True)),
                (
                    "timezone",
                    models.CharField(
                        default="America/New_York",
                        max_length=32,
                        validators=[
                            user_profiles.models.validators.timezone_validation
                        ],
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            user_profiles.models.validators.experience_validation
                        ],
                    ),
                ),
                (
                    "interests",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=250,
                        validators=[
                            user_profiles.models.validators.interests_validation
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True, default="")),
            ],
        ),
    ]
