# Generated by Django 4.1.7 on 2023-03-29 05:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user_profiles.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("first_name", models.TextField(default="")),
                ("last_name", models.TextField(default="")),
            ],
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                validators=[user_profiles.models.validators.gender_validation],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender_focus",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("E", "Everyone")],
                default="E",
                max_length=1,
                validators=[user_profiles.models.validators.gender_focus_validation],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="user_profiles.user",
            ),
        ),
    ]
