# Generated by Django 4.1.7 on 2023-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
