# Generated by Django 4.1.7 on 2023-04-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.TextField(default=""),
        ),
    ]
