# Generated by Django 4.1.7 on 2023-04-05 18:48

from django.db import migrations, models
import user_profiles.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0005_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                validators=[user_profiles.models.validators.interests_validation],
            ),
        ),
    ]
