# Generated by Django 4.1.7 on 2023-04-06 15:58

from django.db import migrations, models
import user_profiles.models.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0006_alter_userprofile_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="interests",
            field=models.CharField(
                blank=True,
                default="",
                max_length=250,
                validators=[user_profiles.models.validators.interests_validation],
            ),
        ),
    ]
