# Generated by Django 4.1.7 on 2023-04-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user_profiles", "0007_alter_userprofile_interests"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="user_profiles.user",
                    ),
                ),
                ("feedback", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="music_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sounds_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
