# Generated by Django 4.1.7 on 2023-03-24 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GPTUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_tokens", models.IntegerField(default=0)),
                ("story_tokens", models.IntegerField(default=0)),
                ("summarizer_tokens", models.IntegerField(default=0)),
                ("indicator_vector", models.CharField(max_length=100)),
                ("indicator_version", models.CharField(max_length=10)),
                ("chat_history_length", models.IntegerField(default=0)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_profiles.botprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "bot", "chat_history_length")},
            },
        ),
    ]
