# Generated by Django 4.1.7 on 2023-04-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_profiles", "0002_remove_botprofile_profile_image"),
        ("user_profiles", "0007_alter_userprofile_interests"),
    ]

    operations = [
        migrations.CreateModel(
            name="GPTUsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indicator_tokens", models.IntegerField(default=0)),
                ("story_tokens", models.IntegerField(default=0)),
                ("summarizer_tokens", models.IntegerField(default=0)),
                ("indicator_vector", models.CharField(max_length=100)),
                ("indicator_version", models.CharField(max_length=10)),
                ("chat_history_length", models.IntegerField(default=0)),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_profiles.botprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_profiles.user",
                    ),
                ),
            ],
        ),
    ]
