# Generated by Django 4.1.7 on 2023-03-17 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dialog_engine", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PromptRecord",
            new_name="GPTUsageRecord",
        ),
    ]
