# Generated by Django 4.1.7 on 2023-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialog_engine", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gptusagerecord",
            name="bot",
        ),
        migrations.RemoveField(
            model_name="gptusagerecord",
            name="user",
        ),
        migrations.AddField(
            model_name="gptusagerecord",
            name="bot_name",
            field=models.CharField(default="default_bot_name", max_length=50),
        ),
        migrations.AddField(
            model_name="gptusagerecord",
            name="email",
            field=models.CharField(default="email@email.com", max_length=200),
        ),
    ]
