# Generated by Django 4.1.7 on 2023-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dialog_engine",
            "0003_rename_indicator_cost_gptusagerecord_indicator_tokens_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gptusagerecord",
            name="total_tokens",
        ),
        migrations.AddField(
            model_name="gptusagerecord",
            name="summarizer_tokens",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
