# Generated by Django 4.1.7 on 2023-03-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dialog_engine", "0004_remove_gptusagerecord_total_tokens_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gptusagerecord",
            name="summarizer_tokens",
            field=models.IntegerField(default=0),
        ),
    ]
