name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_KEY  }}
          HOSTNAME: 100.25.31.90
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          cat private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            cd ./soulspark &&
            git fetch origin --prune &&
            git checkout main &&
            git reset --hard origin/main &&
            git pull origin main 
            source env/bin/activate
            python -m pip install -r requirements.txt 
            python manage.py migrate
            tmux kill-session -t celery
            tmux kill-session -t beat
            tmux new-session -d -s celery 'celery -A soulspark_backend.celery_app worker --loglevel=info'
            tmux new-session -d -s beat 'celery -A soulspark_backend.celery_app beat'
          '
