name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_KEY  }}
          HOSTNAME: ${{ secrets.IP_ADDRESS }}
          USER_NAME: ubuntu

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          cat private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            tmux kill-session -t django
            tmux kill-session -t daphne
            sudo kill -9 $(sudo lsof -t -i:8080)
            sudo kill -9 $(sudo lsof -t -i:8004)
            cd ./soulspark &&
            git fetch origin --prune &&
            git checkout main &&
            git reset --hard origin/main &&
            git pull origin main 
            source env/bin/activate
            python -m pip install -r requirements.txt
            python manage.py migrate
            tmux new-session -d -s django 'gunicorn soulspark_backend.wsgi -b 0.0.0.0:8080'
            tmux new-session -d -s daphne 'daphne -b 0.0.0.0 -p 8004 soulspark_backend.asgi:application'
          '
